apiVersion: v1
kind: Pod
metadata:
  name: chaos-monkey-pod
  namespace: chaos-monkey
  labels:
    app: chaos-monkey
spec:
  serviceAccountName: api-service-account
  containers:
    - name: chaos-monkey
      image: chaos-monkey:miniKubeTag
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: chaos-monkey-config

