apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-red
  namespace: testing
  labels:
    app: nginx-red
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-red
  template:
    metadata:
      labels:
        app: nginx-red
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
