apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-white
  namespace: testing
  labels:
    app: nginx-white
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-white
  template:
    metadata:
      labels:
        app: nginx-white
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.2
          ports:
            - containerPort: 80
